Vs-eng-update-lockdown-attack-lv-381
Last-Voyage/Aframax pull request #205
Opened 2024-11-07 17:51 UTC by RyanASwanson

https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=6318bb796856bdd60aa045de&selectedIssue=LV-381
A lot of stuff being renamed. Some minor adjustments to the lockdown attack 
Lifetime functionality removed

2024-11-09 02:15 UTC, AlecatEnjoyer approved these changes
approve

2024-11-09 16:04 UTC, astapay approved these changes
yippee!

2024-11-10 15:20 UTC, ASLH68 requested changes

2024-11-10 15:20 UTC, ASLH68 commented on Assets/GameAssets/Boss/BossScripts/Attacks/Lockdown/LockdownAttack.cs
Add self as contributor

2024-11-12 18:34 UTC, ASLH68 approved these changes

2024-11-12 18:34 UTC, ASLH68 commented on Assets/GameAssets/Boss/BossScripts/Attacks/Lockdown/LockdownAttackController.cs
> +// File Name :         RoomTongueAttack.cs
Update file name

2024-11-12 18:34 UTC, ASLH68 commented on Assets/GameAssets/Boss/BossScripts/Attacks/Lockdown/LockdownAttackController.cs
> +    //NOTE: Not sure why this isn't done in a base class but ok. Not changing it now to avoid issues with other attacks
Can remove this comment imo

2024-11-12 18:34 UTC, ASLH68 commented on Assets/GameAssets/Boss/BossScripts/Attacks/Lockdown/LockdownAttackController.cs
> +    //NOTE: Not sure why this is an override and isn't done in the base class.
same here w the comment, doesnt add understanding to the file as is

2024-11-12 18:34 UTC, ASLH68 commented on Assets/GameAssets/Boss/BossScripts/Attacks/Lockdown/LockdownAttackEnemyController.cs
> +// Contributors:       Andrea Swihart-DeCoster
add self as contributor

2024-11-12 22:38 UTC, merged