Vs-eng-update-vine-attack-lv-383
Last-Voyage/Aframax pull request #206
Opened 2024-11-08 01:37 UTC by RyanASwanson

https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=6318bb796856bdd60aa045de&selectedIssue=LV-383
This task took a bit longer than intended (not as long as the github history may suggest, but still a bit) luckily the other attack update was very short so it balances out.

2024-11-09 02:11 UTC, AlecatEnjoyer approved these changes
approved left suggestion

2024-11-09 02:11 UTC, AlecatEnjoyer commented on Assets/GameAssets/Boss/BossScripts/Attacks/Vine/VineAttackController.cs
>  *****************************************************************************/
Couldn't this and VineAttack.cs be combined

2024-11-09 16:06 UTC, astapay approved these changes
wahoo!

2024-11-10 15:26 UTC, ASLH68 requested changes

2024-11-10 15:26 UTC, ASLH68 commented on Assets/GameAssets/Boss/BossScripts/Attacks/AttackWarningZone.cs
Add self as contributor

2024-11-10 15:26 UTC, ASLH68 commented on Assets/GameAssets/Boss/BossScripts/Attacks/AttackWarningZone.cs
> +        print("Start warning zone");
Do we need this print here?

2024-11-10 15:26 UTC, ASLH68 commented on Assets/GameAssets/Boss/BossScripts/Attacks/Vine/VineAttack.cs
> +// Brief Description : Controls the functionality for the bosses vine attack
Update the description on `VineAttack.cs` and `VineAttackController.cs` so it's clear how they differ

2024-11-12 18:38 UTC, ASLH68 approved these changes

2024-11-12 21:03 UTC, merged