vs-eng-Public-method-to-spawn-a-game-object-LV-521
Last-Voyage/Aframax pull request #219
Opened 2024-11-12 19:28 UTC by akalscheur-bradley

Gives multiple ways to spawn in an object:
- Serialized fields for in-editor use
- Function overrides to call it outside of the script
Both allow for spawning with or without a parent

2024-11-12 20:18 UTC, RyanASwanson requested changes
Some of the variable names are a bit generic and vague. Functionality wise no complaints. I gotta get more and more picky with code as this has gone on because I have less to comment on as people get better and better.

2024-11-12 20:18 UTC, RyanASwanson commented on Assets/General/Scripts/UniversalFunctions/ObjectSpawner.cs
> +    [SerializeField] GameObject _prefab;
perhaps prefab is too vague? Maybe _objectToSpawn or something like that

2024-11-12 20:18 UTC, RyanASwanson commented on Assets/General/Scripts/UniversalFunctions/ObjectSpawner.cs
> +    [SerializeField] Vector3 _position;
Perhaps could be _spawnPosition instead

2024-11-12 20:18 UTC, RyanASwanson commented on Assets/General/Scripts/UniversalFunctions/ObjectSpawner.cs
> +    [SerializeField] Quaternion _rotation;
Perhaps could be _spawnRotation instead

2024-11-12 20:18 UTC, RyanASwanson commented on Assets/General/Scripts/UniversalFunctions/ObjectSpawner.cs
> +    [SerializeField] Transform _parent;
Perhaps could be _spawnedObjectParent

2024-11-12 20:22 UTC, ASLH68 approved these changes

2024-11-13 16:35 UTC, RyanASwanson approved these changes
Left a suggestion, not a requirement. I approve

2024-11-13 16:35 UTC, RyanASwanson commented on Assets/General/Scripts/UniversalFunctions/ObjectSpawner.cs
> +    public void SpawnObject(GameObject prefab, Vector3 position, Quaternion rotation)
Still think that these names can specify 'spawnPosition' and 'spawnRotation' but regardless I approve

2024-11-13 23:48 UTC, AlecatEnjoyer approved these changes
I approve

2024-11-14 22:07 UTC, merged