VMOD public functions
Last-Voyage/Aframax pull request #225
Opened 2024-11-13 21:24 UTC by DavidHenvick

Jira tasks:
https://bradleycapstone.atlassian.net/browse/LV-519?atlOrigin=eyJpIjoiMmQzMjE0ZDY1ZmMxNGFhOGI3ZTc5OGY0OWY1OWZkNWEiLCJwIjoiaiJ9
https://bradleycapstone.atlassian.net/browse/LV-518?atlOrigin=eyJpIjoiMTZjMzllN2MwNDEzNDVhYThlOTQ3MjBhNzVlNzVhMzciLCJwIjoiaiJ9
https://bradleycapstone.atlassian.net/browse/LV-517?atlOrigin=eyJpIjoiMDlmNDExMmQ5NGI3NDZhYWE2N2UzMWJmYjY2OWViYzkiLCJwIjoiaiJ9

Documentation: https://docs.google.com/document/d/1qyV8T-uRBneLjsCzB8W84C3wD3FJ1SjfEBJIeWANhbo/edit?pli=1&tab=t.z7tsfso1cbvo

Needed parts:
Testing scene: Audio Manager Testing Scene
Important scripts/objects: AudioManager and AudioManagerTester

To test, just start scene, click the buttons : )

2024-11-13 23:13 UTC, RyanASwanson requested changes
Just a few comments about adhering to our code standards

2024-11-13 23:13 UTC, RyanASwanson commented on Assets/General/Scripts/Managers/UniversalManagers/MainUniversalManagers/AudioManager.cs
> +            Destroy(_audioManager.gameObject);
Part of our code documentation states that we should use always use brackets.

2024-11-13 23:13 UTC, RyanASwanson commented on Assets/General/Scripts/Managers/UniversalManagers/MainUniversalManagers/AudioManager.cs
> +            _audioPairs.TryGetValue(reference, out audioEvent);
Same as the previous comment

2024-11-13 23:13 UTC, RyanASwanson commented on Assets/General/Scripts/Managers/UniversalManagers/MainUniversalManagers/TestingScript/AudioManagerTester.cs
> +public class AudioManagerTester : MonoBehaviour
Seeing as this is a testing class I don't have comments, just don't forget to get rid of it when you are done with it after reviews

2024-11-13 23:13 UTC, RyanASwanson commented on Assets/General/Scripts/Managers/UniversalManagers/MainUniversalManagers/AudioManager.cs
> +    public void StopAmbientSound(EventInstance instance, bool fade = false)
Booleans begin with words such as 'is' 'does' 'can' etc.

2024-11-13 23:31 UTC, RyanASwanson approved these changes
Yippee 🎊

2024-11-13 23:41 UTC, AlecatEnjoyer approved these changes
I approve

2024-11-14 21:45 UTC, ASLH68 commented on Assets/General/Scripts/Managers/UniversalManagers/MainUniversalManagers/AudioManagment/StoryBeatAudioManager.cs
> +using FMOD.Studio;
File header

2024-11-14 21:45 UTC, ASLH68 commented on Assets/General/Scripts/Managers/UniversalManagers/MainUniversalManagers/AudioManagment/StoryBeatAudioManager.cs
> +public class AudioManagerTester : MonoBehaviour
Class XML Comment

2024-11-14 21:45 UTC, ASLH68 commented on Assets/General/Scripts/Managers/UniversalManagers/MainUniversalManagers/AudioManagment/StoryBeatAudioManager.cs
> +    [SerializeField] AudioManager Manager;
add private specifier and update naming to the proper convention `_audioManager`

2024-11-14 21:45 UTC, ASLH68 commented on Assets/General/Scripts/Managers/UniversalManagers/MainUniversalManagers/AudioManagment/StoryBeatAudioManager.cs
> +    public void PlayOneshotSound(int index)
XML Comment

2024-11-14 21:45 UTC, ASLH68 commented on Assets/General/Scripts/Managers/UniversalManagers/MainUniversalManagers/AudioManagment/StoryBeatAudioManager.cs
> +    public void PlayAmbient(int index)
XML Comment

2024-11-14 21:46 UTC, ASLH68 commented on Assets/General/Scripts/Managers/UniversalManagers/MainUniversalManagers/AudioManagment/StoryBeatAudioManager.cs
> +    public void StopAmbient()
XML Comment

2024-11-14 21:48 UTC, ASLH68 approved these changes

2024-11-14 21:57 UTC, merged