Vs-Des-HideInInspector-LV-558
Last-Voyage/Aframax pull request #246
Opened 2024-11-17 21:00 UTC by Lazydev114

Jira Link - https://bradleycapstone.atlassian.net/browse/LV-558
Description - should take damage is hidden in inspector now
Best tested by looking at the player prefab to see if the variable is visible on the player health script

2024-11-17 21:35 UTC, ASLH68 requested changes

2024-11-17 21:35 UTC, ASLH68 commented on Assets/GameAssets/Player/PlayerScripts/PlayerHealth.cs
>      public bool _shouldTakeDamage = true;//Nabil made this change
incorrect naming convention

2024-11-18 15:29 UTC, AlecatEnjoyer approved these changes
i simply approve

2024-11-18 17:03 UTC, ASLH68 approved these changes

2024-11-19 03:53 UTC, merged